package com.example.shelfplayer.core.datastore.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * PRODUCT_SPEC AUTH-003 — encrypts a token with a key that never leaves the Android Keystore.
 *
 * ADR-0007 records the decision to use the Keystore API directly rather than
 * `androidx.security:security-crypto`, whose only releases are alphas. That choice means the details
 * below are ours to get right, so each one is stated with its reason.
 *
 * The key is generated in the `AndroidKeyStore` provider and is not extractable: this class can ask
 * for encryption and decryption, but it cannot read the key material, and neither can anything that
 * later reads the app's private storage.
 */
@Singleton
class TokenCipher @Inject constructor() {

    /**
     * Encrypts [plaintext] and returns the IV prefixed to the ciphertext.
     *
     * The IV is generated by the platform rather than supplied. GCM is catastrophically weak if an IV
     * is ever reused with the same key, and letting the provider choose removes the chance of this
     * code reusing one.
     */
    fun encrypt(plaintext: String): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val iv = cipher.iv
        require(iv.size == IV_LENGTH) { "unexpected GCM IV length: ${iv.size}" }
        return iv + cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
    }

    /**
     * Reverses [encrypt], or returns `null` if the value cannot be decrypted.
     *
     * `null` rather than an exception, because every reason this fails has the same correct response:
     * treat the stored session as gone and require signing in again (`AUTH-004`). The causes are all
     * ordinary — a lock-screen change or a restore onto a new device destroys the key, and a truncated
     * record cannot be authenticated — so none of them is a crash.
     *
     * GCM is what makes returning `null` safe: an authenticated mode rejects a tampered ciphertext
     * instead of returning plausible-looking bytes that would then be sent to a server as a token.
     */
    @Suppress("TooGenericExceptionCaught", "SwallowedException")
    fun decrypt(encrypted: ByteArray): String? {
        if (encrypted.size <= IV_LENGTH) return null
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key(),
                GCMParameterSpec(TAG_LENGTH_BITS, encrypted, 0, IV_LENGTH),
            )
            val plaintext = cipher.doFinal(encrypted, IV_LENGTH, encrypted.size - IV_LENGTH)
            String(plaintext, Charsets.UTF_8)
        } catch (failure: GeneralSecurityException) {
            // Deliberately not logged with any detail: PRODUCT_SPEC 14.5, and the exception type is
            // the only interesting part. The caller reports the re-authentication, not this class.
            null
        } catch (failure: IllegalArgumentException) {
            null
        }
    }

    /** Drops the key, making every previously stored token permanently unreadable. */
    fun clear() {
        keyStore().deleteEntry(KEY_ALIAS)
    }

    private fun key(): SecretKey {
        val store = keyStore()
        (store.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.secretKey?.let { return it }
        return generateKey()
    }

    private fun generateKey(): SecretKey = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER).apply {
        init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                // Sessions are renewed in the background and downloads run without the user present,
                // so a key gated on device unlock would break AUTH-004 renewal rather than protect it.
                .setUserAuthenticationRequired(false)
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
    }.generateKey()

    private fun keyStore(): KeyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "shelfplayer.session.v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_LENGTH_BITS = 128
        const val IV_LENGTH = 12
    }
}
