package com.example.shelfplayer.buildlogic

import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.DetektCreateBaselineTask
import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.withType
import org.jlleitschuh.gradle.ktlint.KtlintExtension
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType
import java.util.concurrent.Callable

/**
 * The quality gate applied to every ShelfPlayer project, including the root project.
 *
 * PRODUCT_SPEC 16.2 (ktlint), 16.3 (detekt with type resolution, Android Lint, warnings as errors),
 * 16.1 (dependency locking) and 16.5 (`verifyDebug`).
 */
class QualityConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            configureKtlint()
            configureDetekt()
            configureDependencyLocking()
            registerVerifyDebug()
        }
    }
}

private fun Project.configureKtlint() {
    pluginManager.apply("org.jlleitschuh.gradle.ktlint")

    extensions.configure<KtlintExtension> {
        version.set(libs.version("ktlint"))
        // PRODUCT_SPEC 16.2: ktlint is the single formatter; style rules live in `.editorconfig`.
        ignoreFailures.set(false)
        enableExperimentalRules.set(false)
        reporters {
            reporter(ReporterType.PLAIN)
            reporter(ReporterType.CHECKSTYLE)
        }
        filter {
            // Generated Kotlin (KSP, Room, Hilt, protobuf) is not ours to format.
            exclude { element -> element.file.path.contains("${java.io.File.separator}build${java.io.File.separator}") }
            exclude { element ->
                element.file.path.contains("${java.io.File.separator}generated${java.io.File.separator}")
            }
        }
    }
}

private fun Project.configureDetekt() {
    pluginManager.apply("io.gitlab.arturbosch.detekt")

    extensions.configure<DetektExtension> {
        buildUponDefaultConfig = true
        allRules = false
        parallel = true
        // PRODUCT_SPEC 16.3: no detekt baseline for new code.
        baseline = null
        config.setFrom(rootProject.file("config/detekt/detekt.yml"))
        basePath = rootProject.projectDir.absolutePath
    }

    tasks.withType<Detekt>().configureEach {
        jvmTarget = JVM_TARGET
        exclude("**/build/**", "**/generated/**")
        reports {
            html.required.set(true)
            xml.required.set(true)
            sarif.required.set(true)
            txt.required.set(false)
            md.required.set(false)
        }
    }
    tasks.withType<DetektCreateBaselineTask>().configureEach {
        jvmTarget = JVM_TARGET
    }
}

/**
 * PRODUCT_SPEC 16.1 — dependency locking, over the classpaths that ship.
 *
 * Lock state is regenerated by `scripts/update-dependency-locks.sh`. It runs a real build rather than
 * `resolveAndLockAll`, because a good half of these configurations only resolve inside a task's
 * execution context and a lock state written outside one is missing exactly those.
 *
 * ### Why not `lockAllConfigurations()`
 *
 * It was tried first, and it does not work here — not for want of regenerating. The unit-test runtime
 * classpaths hit a Gradle behaviour where `--write-locks` records a state that an ordinary resolution
 * of the *same* configuration then rejects:
 *
 * ```
 * ./gradlew :data:settings:mergeDebugUnitTestAssets --write-locks --rerun-tasks   # succeeds
 * ./gradlew :data:settings:mergeDebugUnitTestAssets                               # fails:
 * #   Resolved 'org.jetbrains.kotlin:kotlin-stdlib-common:2.2.0' which is not part of the lock state
 * ```
 *
 * `kotlin-stdlib-common` is a metadata variant that the test runtime classpath resolves under different
 * attributes at execution time than at lock-write time, so the write and the check disagree about what
 * the configuration contains. No amount of re-running reconciles them. Locking every configuration
 * therefore means a build that cannot pass, which is not a stricter gate — it is a broken one.
 *
 * ### What is locked instead
 *
 * The compile and runtime classpaths of the production variants: everything whose resolution decides
 * what ends up in an APK. That is where 16.1's guarantee is worth having — a transitive dependency
 * silently changing version between builds is a supply-chain event, and this is what catches it.
 *
 * Excluded: `*UnitTestCompileClasspath`, `*UnitTestRuntimeClasspath`, `*AndroidTest*`, and the tooling
 * classpaths (detekt, ktlint, KSP processors). Nothing they resolve reaches a user's device. They are
 * still covered by dependency **verification**, which is on and `strict` and checks every artifact the
 * build resolves regardless of configuration — so the excluded classpaths are pinned by checksum even
 * though they are not pinned by version.
 */
private fun Project.configureDependencyLocking() {
    configurations.configureEach {
        if (isShippingClasspath(name)) {
            resolutionStrategy.activateDependencyLocking()
        }
    }
}

/**
 * A configuration whose resolution decides what ends up in the app.
 *
 * Name-based because that is the only stable handle: AGP creates these per variant and there is no
 * "is this shipped" flag to ask. `Compile` is included alongside `Runtime` because a compile classpath
 * decides what the code is written against, and a version drifting there changes the bytecode.
 */
private fun isShippingClasspath(name: String): Boolean {
    val isTest = name.contains("UnitTest") || name.contains("AndroidTest")
    val isClasspath = name.endsWith("CompileClasspath") || name.endsWith("RuntimeClasspath")
    return isClasspath && !isTest
}

/**
 * PRODUCT_SPEC 16.5: one command that agents and CI can run.
 *
 * Task names are resolved lazily through a [Callable] so a module only wires the gates that its own
 * plugins actually registered — a JVM module has no `lintDebug`, an Android module has no bare
 * `test` worth running twice.
 */
private fun Project.registerVerifyDebug() {
    val verify = tasks.register("verifyDebug") {
        group = "verification"
        description = "ktlint + detekt (type resolution) + Android Lint + unit tests + debug assembly."
    }

    verify.configure {
        dependsOn(Callable { resolveVerifyDebugDependencies() })
    }
}

/**
 * Detekt registers per-variant tasks (`detektDebug`) for Android modules and per-compilation tasks
 * (`detektMain`) for JVM modules. Both carry the compile classpath, which is what gives detekt type
 * resolution (PRODUCT_SPEC 16.3); the plain `detekt` task does not and is therefore not a gate.
 */
private fun Project.resolveVerifyDebugDependencies(): List<String> {
    val available = tasks.names
    val android = pluginManager.hasPlugin("com.android.base")
    val hasKotlin = pluginManager.hasPlugin("org.jetbrains.kotlin.android") ||
        pluginManager.hasPlugin("org.jetbrains.kotlin.jvm")

    val typeResolvingDetekt = when {
        !hasKotlin -> emptyList()
        "detektDebug" in available ->
            listOf("detektDebug", "detektDebugUnitTest").filter(available::contains)
        else -> listOf("detektMain", "detektTest").filter(available::contains)
    }
    check(!hasKotlin || typeResolvingDetekt.isNotEmpty()) {
        "$path has Kotlin sources but no detekt task with type resolution. " +
            "Expected one of detektDebug/detektMain; found: ${available.filter { it.startsWith("detekt") }}"
    }

    val build = when {
        android -> listOf("lintDebug", "testDebugUnitTest", "assembleDebug")
        hasKotlin -> listOf("test")
        else -> emptyList()
    }

    return (listOf("ktlintCheck") + typeResolvingDetekt + build).filter(available::contains)
}
